apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: idp-ldap-example
      ldap:
        attributes:
          email:
            - mail
          id:
            - dn
          name:
            - cn
          preferredUsername:
            - uid
        bindDN: uid=ocp-bind,cn=users,dc=example,dc=com
        bindPassword:
          name: idp-secret-example
        ca:
          name: idp-ca-example
        insecure: false
        url: ldap://ldap.example.com/dc=example,dc=com?uid?sub?(memberOf=cn=ocp-users,cn=groups,dc=example,dc=com)
      mappingMethod: claim
      type: LDAP
