apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: idp-hatpasswd-example
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: idp-secret-example
