apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    label.name: label-example
  name: keycloak-instance-example
  namespace: namespace-example
spec:
  #extensions:
  #- https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  #- /PATH/FOR/MY/COLOR-THEME/JAR/
  externalAccess:
    enabled: true
    # Setting Host in External Access on OpenShift is prohibited
    #host: sso-example.apps.openshift.example.com
    tlsTermination: reencrypt
  instances: 1
